### ISSUE TITLE
URLs white on white

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/reveal-md#3]
It looks like the CS theme styles links as white text on a white background, which has slight legibility issues :)

I think the problem is that the CS theme was based on the _black_ theme, despite having a light background (a better choice may have been the _white_ theme).

**Comment by frankscholten** [comment]
Indeed. When you print to PDF you can see remnants of the black theme. https://github.com/ContainerSolutions/reveal-md/issues/7

**Comment by idcrosby** [comment]
Fixed here: https://github.com/ContainerSolutions/reveal-md/commit/d4667373d5480cb3f4d3c2a0acb2af23f1f96e99
@frankscholten  can you verify this works for you as well and close the issue?

**Comment by frankscholten** [comment]
LGTM thx @idcrosby
